### ISSUE TITLE
Redo the API handler

### ISSUE THREAD

**Issue by coltoneshaw** [ethanopp/3C-Portfolio-Manager#10]
Right now the handler limits at 5k deals. 3Commas returns oldest deals first. This means if you have 10k deals to look at, the dashboards focus on most recent deals but you only get to see the oldest deals. 

We essentially need to query all deals and drop the first set up to 5k or find a way to get 3C to query on dates only.

**Comment by ethanopp** [comment]
Query parameter “order”=“closed_at”

https://github.com/3commas-io/3commas-official-api-docs/blob/master/deals_api.md#user-deals-permission-bots_read-security-signed

**Comment by coltoneshaw** [comment]
Nice! I thought I read it only did oldest first and no params were available, I must have misread that somewhere. I'm redoing some parts of the API handler and I can update the query strings.
